server:
  port: ${SERVER_PORT:8080}
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}