name: 'Pull Request Title and Commit Check'
on:
  pull_request:
    branches:
      - main
    types: [ opened, reopened, synchronize, ready_for_review ]

jobs:
  check-pull-request-title:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v5
        with:
          validateSingleCommit: true
          validateSingleCommitMatchesPrTitle: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}